version: '3.9'

networks:
  postgresql-network:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres
    container_name: db-postgres
    networks:
      - postgresql-network
    restart: always
    env_file:
      - variables.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup:/backup